language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  keep-history: false
  on:
    branch: master
  repo: promptfu/promptfu.com
  target-branch: master

before_script:
  - "npm install -g gatsby"
  - "npm install"

script:
  - "npm run test"
  - "npm run build"

notifications:
  email:
    recipients:
      - ci@promptfu.com
    on_sucess: always
    on_failure: always
